import streamlit as st

st.title("About")
st.markdown("""
This tool was created as an experiment with ChatGPT. All responses are generated by ChatGPT version 3.5,
and it's use and resulting content follow the OpenAI Terms of Use found [here](https://openai.com/policies/terms-of-use).

By using this service, you accept there is no guarantee, implied or otherwise, as to the accuracy or value of the
responses generated by the system, or the availability of the system. In fact, it will probably be shut off
permanently tomorrow.

If you are interested in a more powerful version, you can help define its feature [here](/Pro_version)
""")